Add force-yes

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,16 +1,25 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-set -e # fail fast
+# fail fast
+set -e
 
-# parse params
-BUILD_DIR=/app
+# debug
+# set -x
+
+# parse and derive params
+BUILD_DIR=$1
 CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-BUILDPACK_NAME=pango
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
 
-# use pigz if available for (potentially) faster decompression
-type pigz > /dev/null 2>&1 && alias tar='tar --use-compress-program=pigz'
+function topic() {
+  echo "-----> $*"
+}
 
 function indent() {
   c='s/^/       /'
@@ -20,69 +29,41 @@ function indent() {
   esac
 }
 
-function vendor() {
-  binary="$1"
-  path="$2"
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
 
-  echo "Fetching $binary" | indent
-  mkdir -p $path
-  curl $binary -s -o - | tar xz -C $path -f -
+mkdir -p "$APT_CACHE_DIR/archives/partial"
+mkdir -p "$APT_STATE_DIR/lists/partial"
 
-  if [ -d "$path/bin" ]; then
-    export PATH=$path/bin:$PATH
-  fi
+APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
 
-  if [ -d "$path/lib/pkgconfig" ]; then
-    echo "Found $path/lib/pkgconfig"
-    # pkg-config should handle compiler options (if used)
-    export PKG_CONFIG_PATH="$path/lib/pkgconfig:$PKG_CONFIG_PATH"
-    echo $PKG_CONFIG_PATH
-  fi
+topic "Updating apt caches"
+apt-get $APT_OPTIONS update | indent
 
-  # standard paths
-  export CPPPATH="$path/include:$CPPPATH"
-  export CPATH="$path/include:$CPATH"
-  export LIBRARY_PATH="$path/lib:$LIBRARY_PATH"
+for PACKAGE in $(cat $BUILD_DIR/Aptfile); do
+  topic "Fetching .debs for $PACKAGE"
+  apt-get $APT_OPTIONS -y --force-yes -d install $PACKAGE | indent
+done
 
-  export LD_LIBRARY_PATH="$path/lib:$LD_LIBRARY_PATH"
-}
+mkdir -p $BUILD_DIR/.apt
 
-echo "-----> Vendoring binaries"
-vendor "https://s3.amazonaws.com/mojodna-heroku/cairo-1.12.16-1.tar.gz"  "$BUILD_DIR/vendor/cairo"
-vendor "https://s3.amazonaws.com/mojodna-heroku/freetype-2.5.0-1.tar.gz" "$BUILD_DIR/vendor/freetype"
-vendor "http://miadzin.org/libgdk-pixbuf2.0.tgz"  "$BUILD_DIR/vendor/gdk-pixbuf"
-vendor "http://miadzin.org/libpixman-1.tgz"  "$BUILD_DIR/vendor/pixman-1"
-vendor "http://miadzin.org/libpango-1.30.0.tgz"  "$BUILD_DIR/vendor/pango"
+for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
+  topic "Installing $(basename $DEB)"
+  dpkg -x $DEB $BUILD_DIR/.apt/
+done
 
-echo "-----> Configuring build environment"
-
-cat <<EOF > export
-export PATH="$PATH:\$PATH"
-export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:$LD_LIBRARY_PATH"
-export LIBRARY_PATH="\$LIBRARY_PATH:$LIBRARY_PATH"
-export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:$PKG_CONFIG_PATH"
-export CPPPATH="\$CPPPATH:$CPPPATH"
-export CPATH="\$CPATH:$CPATH"
-EOF
-
-echo "-----> Building runtime environment"
+topic "Writing profile script"
 mkdir -p $BUILD_DIR/.profile.d
-
-cat <<EOF > $BUILD_DIR/.profile.d/$BUILDPACK_NAME.sh
-export PATH="${PATH//$BUILD_DIR//app}:\$PATH"
-export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:${LD_LIBRARY_PATH//$BUILD_DIR//app}"
-export LIBRARY_PATH="\$LIBRARY_PATH:${LIBRARY_PATH//$BUILD_DIR//app}"
-export PKG_CONFIG_PATH="\$PKG_CONFIG_PATH:${PKG_CONFIG_PATH//$BUILD_DIR//app}"
-export CPPPATH="\$CPPPATH:${CPPPATH//$BUILD_DIR//app}"
-export CPATH="\$CPATH:${CPATH//$BUILD_DIR//app}"
+cat <<EOF >$BUILD_DIR/.profile.d/000_apt.sh
+export PATH="\$HOME/.apt/usr/bin:$PATH"
+export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib:\$LD_LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/.apt/usr/include:\$INCLUDE_PATH"
+export CPATH="\$INCLUDE_PATH"
+export CPPPATH="\$INCLUDE_PATH"
 EOF
 
-echo "-----> Prove it worked"
-echo `pkg-config --static --libs glib-2.0 gdk-pixbuf-2.0 cairo pango`
-echo `pkg-config --cflags glib-2.0 gdk-pixbuf-2.0 cairo pango`
-echo $PATH
-echo $LD_LIBRARY_PATH
-echo $LIBRARY_PATH
-echo $PKG_CONFIG_PATH
-echo $CPPPATH
-echo $CPATH
+export PATH="$BUILD_DIR/.apt/usr/bin:$PATH"
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib:$LD_LIBRARY_PATH"
+export INCLUDE_PATH="$BUILD_DIR/.apt/usr/include:$INCLUDE_PATH"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
